export const COUNTRYLIST = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegowina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, the Democratic Republic of the",
  "Cook Islands",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia (Hrvatska)",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "France Metropolitan",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard and Mc Donald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Republic of",
  "Kuwait",
  "Kyrgyzstan",
  "Lao, People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia, The Former Yugoslav Republic of",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova, Republic of",
  "Monaco",
  "Mongolia",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia (Slovak Republic)",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "Spain",
  "Sri Lanka",
  "St. Helena",
  "St. Pierre and Miquelon",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen Islands",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan, Province of China",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna Islands",
  "Western Sahara",
  "Yemen",
  "Yugoslavia",
  "Zambia",
  "Zimbabwe",
];
export const BRAND = "FortifID";
export const TIMEZONES = {
  "Pacific/Midway": "(GMT-11:00) Midway Island",
  "US/Samoa": "(GMT-11:00) Samoa",
  "US/Hawaii": "(GMT-10:00) Hawaii",
  "US/Alaska": "(GMT-09:00) Alaska",
  "US/Pacific": "(GMT-08:00) Pacific Time (US & Canada)",
  "America/Tijuana": "(GMT-08:00) Tijuana",
  "US/Arizona": "(GMT-07:00) Arizona",
  "US/Mountain": "(GMT-07:00) Mountain Time (US & Canada)",
  "America/Chihuahua": "(GMT-07:00) Chihuahua",
  "America/Mazatlan": "(GMT-07:00) Mazatlan",
  "America/Mexico_City": "(GMT-06:00) Mexico City",
  "America/Monterrey": "(GMT-06:00) Monterrey",
  "Canada/Saskatchewan": "(GMT-06:00) Saskatchewan",
  "US/Central": "(GMT-06:00) Central Time (US & Canada)",
  "US/Eastern": "(GMT-05:00) Eastern Time (US & Canada)",
  "US/East-Indiana": "(GMT-05:00) Indiana (East)",
  "America/Bogota": "(GMT-05:00) Bogota",
  "America/Lima": "(GMT-05:00) Lima",
  "America/Caracas": "(GMT-04:30) Caracas",
  "Canada/Atlantic": "(GMT-04:00) Atlantic Time (Canada)",
  "America/La_Paz": "(GMT-04:00) La Paz",
  "America/Santiago": "(GMT-04:00) Santiago",
  "Canada/Newfoundland": "(GMT-03:30) Newfoundland",
  "America/Buenos_Aires": "(GMT-03:00) Buenos Aires",
  Greenland: "(GMT-03:00) Greenland",
  "Atlantic/Stanley": "(GMT-02:00) Stanley",
  "Atlantic/Azores": "(GMT-01:00) Azores",
  "Atlantic/Cape_Verde": "(GMT-01:00) Cape Verde Is.",
  "Africa/Casablanca": "(GMT) Casablanca",
  "Europe/Dublin": "(GMT) Dublin",
  "Europe/Lisbon": "(GMT) Lisbon",
  "Europe/London": "(GMT) London",
  "Africa/Monrovia": "(GMT) Monrovia",
  "Europe/Amsterdam": "(GMT+01:00) Amsterdam",
  "Europe/Belgrade": "(GMT+01:00) Belgrade",
  "Europe/Berlin": "(GMT+01:00) Berlin",
  "Europe/Bratislava": "(GMT+01:00) Bratislava",
  "Europe/Brussels": "(GMT+01:00) Brussels",
  "Europe/Budapest": "(GMT+01:00) Budapest",
  "Europe/Copenhagen": "(GMT+01:00) Copenhagen",
  "Europe/Ljubljana": "(GMT+01:00) Ljubljana",
  "Europe/Madrid": "(GMT+01:00) Madrid",
  "Europe/Paris": "(GMT+01:00) Paris",
  "Europe/Prague": "(GMT+01:00) Prague",
  "Europe/Rome": "(GMT+01:00) Rome",
  "Europe/Sarajevo": "(GMT+01:00) Sarajevo",
  "Europe/Skopje": "(GMT+01:00) Skopje",
  "Europe/Stockholm": "(GMT+01:00) Stockholm",
  "Europe/Vienna": "(GMT+01:00) Vienna",
  "Europe/Warsaw": "(GMT+01:00) Warsaw",
  "Europe/Zagreb": "(GMT+01:00) Zagreb",
  "Europe/Athens": "(GMT+02:00) Athens",
  "Europe/Bucharest": "(GMT+02:00) Bucharest",
  "Africa/Cairo": "(GMT+02:00) Cairo",
  "Africa/Harare": "(GMT+02:00) Harare",
  "Europe/Helsinki": "(GMT+02:00) Helsinki",
  "Europe/Istanbul": "(GMT+02:00) Istanbul",
  "Asia/Jerusalem": "(GMT+02:00) Jerusalem",
  "Europe/Kiev": "(GMT+02:00) Kyiv",
  "Europe/Minsk": "(GMT+02:00) Minsk",
  "Europe/Riga": "(GMT+02:00) Riga",
  "Europe/Sofia": "(GMT+02:00) Sofia",
  "Europe/Tallinn": "(GMT+02:00) Tallinn",
  "Europe/Vilnius": "(GMT+02:00) Vilnius",
  "Asia/Baghdad": "(GMT+03:00) Baghdad",
  "Asia/Kuwait": "(GMT+03:00) Kuwait",
  "Africa/Nairobi": "(GMT+03:00) Nairobi",
  "Asia/Riyadh": "(GMT+03:00) Riyadh",
  "Europe/Moscow": "(GMT+03:00) Moscow",
  "Asia/Tehran": "(GMT+03:30) Tehran",
  "Asia/Baku": "(GMT+04:00) Baku",
  "Europe/Volgograd": "(GMT+04:00) Volgograd",
  "Asia/Muscat": "(GMT+04:00) Muscat",
  "Asia/Tbilisi": "(GMT+04:00) Tbilisi",
  "Asia/Yerevan": "(GMT+04:00) Yerevan",
  "Asia/Kabul": "(GMT+04:30) Kabul",
  "Asia/Karachi": "(GMT+05:00) Karachi",
  "Asia/Tashkent": "(GMT+05:00) Tashkent",
  "Asia/Kolkata": "(GMT+05:30) Kolkata",
  "Asia/Kathmandu": "(GMT+05:45) Kathmandu",
  "Asia/Yekaterinburg": "(GMT+06:00) Ekaterinburg",
  "Asia/Almaty": "(GMT+06:00) Almaty",
  "Asia/Dhaka": "(GMT+06:00) Dhaka",
  "Asia/Novosibirsk": "(GMT+07:00) Novosibirsk",
  "Asia/Bangkok": "(GMT+07:00) Bangkok",
  "Asia/Jakarta": "(GMT+07:00) Jakarta",
  "Asia/Krasnoyarsk": "(GMT+08:00) Krasnoyarsk",
  "Asia/Chongqing": "(GMT+08:00) Chongqing",
  "Asia/Hong_Kong": "(GMT+08:00) Hong Kong",
  "Asia/Kuala_Lumpur": "(GMT+08:00) Kuala Lumpur",
  "Australia/Perth": "(GMT+08:00) Perth",
  "Asia/Singapore": "(GMT+08:00) Singapore",
  "Asia/Taipei": "(GMT+08:00) Taipei",
  "Asia/Ulaanbaatar": "(GMT+08:00) Ulaan Bataar",
  "Asia/Urumqi": "(GMT+08:00) Urumqi",
  "Asia/Irkutsk": "(GMT+09:00) Irkutsk",
  "Asia/Seoul": "(GMT+09:00) Seoul",
  "Asia/Tokyo": "(GMT+09:00) Tokyo",
  "Australia/Adelaide": "(GMT+09:30) Adelaide",
  "Australia/Darwin": "(GMT+09:30) Darwin",
  "Asia/Yakutsk": "(GMT+10:00) Yakutsk",
  "Australia/Brisbane": "(GMT+10:00) Brisbane",
  "Australia/Canberra": "(GMT+10:00) Canberra",
  "Pacific/Guam": "(GMT+10:00) Guam",
  "Australia/Hobart": "(GMT+10:00) Hobart",
  "Australia/Melbourne": "(GMT+10:00) Melbourne",
  "Pacific/Port_Moresby": "(GMT+10:00) Port Moresby",
  "Australia/Sydney": "(GMT+10:00) Sydney",
  "Asia/Vladivostok": "(GMT+11:00) Vladivostok",
  "Asia/Magadan": "(GMT+12:00) Magadan",
  "Pacific/Auckland": "(GMT+12:00) Auckland",
  "Pacific/Fiji": "(GMT+12:00) Fiji",
};
export const STATELIST = [
  "AL",
  "AK",
  "AR",
  "AS",
  "AZ",
  "CA",
  "CO",
  "CT",
  "DC",
  "DE",
  "FL",
  "FM",
  "GA",
  "GU",
  "HI",
  "IA",
  "ID",
  "IL",
  "IN",
  "KS",
  "KY",
  "LA",
  "MA",
  "MD",
  "ME",
  "MH",
  "MI",
  "MN",
  "MO",
  "MP",
  "MS",
  "MT",
  "NC",
  "ND",
  "NE",
  "NH",
  "NJ",
  "NM",
  "NV",
  "NY",
  "OH",
  "OK",
  "OR",
  "PA",
  "PR",
  "PW",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VA",
  "VI",
  "VT",
  "WA",
  "WI",
  "WV",
  "WY",
];
export const SCHEMES = {
  "#FE8900": "#FE8900",
  "#339E64": "#339E64",
  "#0376BC": "#0376BC",
  "#142D53": "#142D53",
  "#DE4A0B": "#DE4A0B",
  "#324750": "#324750",
  "#00bdbb": "#00bdbb",
};
export const EMPLOYEMENTTYPES = {
  "Full-Time": "Full-Time",
  "Part-Time": "Part-Time",
  Seasonal: "Seasonal",
  Temporary: "Temporary",
  Internship: "Internship",
  "At-Will": "At-Will",
  Other: "Other",
};
export const INCOMETYPES = {
  Unemployed: "Unemployed",
  Employed: "Employed",
  "Self Employed": "Self Employed",
  BusinessOwner: "Business Owner",
  Retired: "Retired",
  Student: "Student",
  Military: "Military",
  Other: "Other",
};
export const OWNERTYPES = {
  Corporation: "Corporation",
  Partnership: "Partnership",
  "Sole Proprietor": "Sole Proprietor",
  "Limited Partnership": "Limited Partnership",
  "General Partnership": "General Partnership",
  "Limited Liability Company": "Limited Liability Company",
  "Limited Liability Partnership": "Limited Liability Partnership",
  "Subchapter S Corporation": "Subchapter S Corporation",
  "Subchapter C Corporation": "Subchapter C Corporation",
  "Limited Liability, Limited Partnership":
    "Limited Liability, Limited Partnership",
  "Mutual Company": "Mutual Company",
  Trust: "Trust",
  "Low Profit Limited Liability Company (available 2009)":
    "Low Profit Limited Liability Company (available 2009)",
  "Other Liability Type": "Other Liability Type",
};
export const BUSINESSTYPES = {
  Agency: "Agency",
  Association: "Association",
  Authority: "Authority",
  Brokerage: "Brokerage",
  "Charitable/Fundraising Organization": "Charitable/Fundraising Organization",
  "City Government": "City Government",
  "Civic Organization": "Civic Organization",
  "Collection Agency": "Collection Agency",
  Cooperative: "Cooperative",
  "County Government": "County Government",
  "Credit Union": "Credit Union",
  "District Government": "District Government",
  "Federal Government": "Federal Government",
  "Financial Institution": "Financial Institution",
  Franchise: "Franchise",
  Government: "Government",
  Insurance: "Insurance",
  "Local Government": "Local Government",
  Medical: "Medical",
  "Medical Professional": "Medical Professional",
  Military: "Military",
  "Mutual Benefit": "Mutual Benefit",
  Professional: "Professional",
  "Public Benefit": "Public Benefit",
  Railroad: "Railroad",
  "Religious Institution": "Religious Institution",
  "Rental Agency": "Rental Agency",
  Residential: "Residential",
  School: "School",
  "State Government": "State Government",
  "Tribal Government": "Tribal Government",
};
export const FLAGGED_CODES = {
  "FID-SSNCHK-VALID": {
    text: "SSN Verified",
    refer: "[Refer: FID-SSNCHK-VALID]",
  },
  "FID-SSNCHK-MISMATCH": {
    text: "SSN Not Verified",
    refer: "[Refer: FID-SSNCHK-MISMATCH]",
  },
  "FID-SSNCHK-UNAVAIL": {
    text: "SSN Unable to Verify",
    refer: "[Refer: FID-SSNCHK-UNAVAIL]",
  },
  "FID-SSNCHK-EXCEPT": {
    text: "SSN Unable to Verify",
    refer: "[Refer: FID-SSNCHK-EXCEPT]",
  },
  "FID-FRAUD-VERIFIED": {
    text: "No fraud warning",
    refer: "[Refer: FID-FRAUD-VERIFIED]",
  },
  "FID-FRAUD-WARNING": {
    text: "Fraud warning",
    refer: "[Refer: FID-FRAUD-WARNING]",
  },
  "FID-FRAUD-EXCEPT": {
    text: "Fraud check did not process",
    refer: "[Refer: FID-FRAUD-EXCEPT]",
  },
  "FID-FRAUD-VICTIM": {
    text: "Fraud victim",
    refer: "[Refer: FID-FRAUD-VICTIM]",
  },
  "FID-FRAUD-BOTH": {
    text: "Fraud warning and victim",
    refer: "[Refer: FID-FRAUD-BOTH]",
  },
  "FID-MATCHASSMNT-0": {
    text: "Name and address cannot be verified",
    refer: "[Refer: FID-MATCHASSMNT-0]",
  },
  "FID-MATCHASSMNT-A": {
    text: "Name and address matches",
    refer: "[Refer: FID-MATCHASSMNT-A]",
  },
  "FID-MATCHASSMNT-B": {
    text: "Name and address matches",
    refer: "[Refer: FID-MATCHASSMNT-B]",
  },
  "FID-MATCHASSMNT-C": {
    text: "Name and address matches",
    refer: "[Refer: FID-MATCHASSMNT-C]",
  },
  "FID-MATCHASSMNT-D": {
    text: "Name and address partially verified",
    refer: "[Refer: FID-MATCHASSMNT-D]",
  },
  "FID-MATCHASSMNT-E": {
    text: "Name and address matches",
    refer: "[Refer: FID-MATCHASSMNT-E]",
  },
  "FID-MATCHASSMNT-F": {
    text: "Name and address partially verified",
    refer: "[Refer: FID-MATCHASSMNT-F]",
  },
  "FID-MATCHASSMNT-G": {
    text: "Name and address partially verified",
    refer: "[Refer: FID-MATCHASSMNT-G]",
  },
  "FID-PHONE-VERIFIED": {
    text: "Applicant verified",
    refer: "[Refer: FID-PHONE-VERIFIED-COMPONENTS and FID-PHONE-ADDRESS-NAME-LINK for details]",
  },
  "FID-PHONE-UNVERIFIED": {
    text: "Applicant not verified - ",
    refer: "[Refer: FID-PHONE-UNVERIFIED-COMPONENTS and FID-PHONE-ADDRESS-NAME-LINK for details]"
  },
  "FID-PHONE-REVIEW": {
    text: "Applicant needs review - ",
    refer: "[Refer: FID-PHONE-VERIFIED-COMPONENTS and FID-PHONE-UNVERIFIED-COMPONENTS and FID-PHONE-ADDRESS-NAME-LINK for details]",
  },
  "FID-DL-EXPLAIN-VERIFIED": {
    text: "All validation requirements passed",
    refer: "[Refer: FID-DL-EXPLAIN-VERIFIED]",
  },
  "FID-DL-EXPLAIN-UNVERIFIED": {
    text: "All validation requirements did not pass - ",
    refer: "[Refer: FID-DL-EXPLAIN-UNVERIFIED]",
  },
};
export const DEMODATA = {
  GreenPathApplicant: {
    first_name: "Joshua",
    middle_name: "D",
    last_name: "Smith",
    dob: "1972-08-19",
    ssn: "778-62-8144",
    address: "3255 ABBEYFIELD LN",
    city: "JACKSONVILLE",
    state: "FL",
    zip: "32277",
    email: "joshuadsmith@email.com",
    phone: "8015551213",
    dl_number: "F202020204503",
    state_issue: "FL",
    exp_date: "01/01/2006",
  },
  RedPathApplicant: {
    first_name: "Tiffany",
    middle_name: "A",
    last_name: "Sanford",
    dob: "2000-04-04",
    ssn: "757-85-7495",
    address: "1714 69TH AV W",
    city: "CAMARILLO",
    state: "CA",
    zip: "93010",
    email: "tiffanysandford@email.net",
    phone: "7652969341",
    dl_number: "F202020204503",
    state_issue: "FL",
    exp_date: "01/01/2006",
  },
  YellowPathApplicant: {
    first_name: "Anne",
    middle_name: "E",
    last_name: "Catero",
    dob: "1971-10-01",
    ssn: "805-14-1893",
    address: "8142 OLD SUNRIDGE DR",
    city: "ELLABELL",
    state: "GA",
    zip: "31308",
    email: "annet@catero.com",
    phone: "4042550181",
    dl_number: "F100055633246",
    state_issue: "FL",
    exp_date: "01/01/2006",
  },
};

export const ROLES = {
  admin: "admin",
  supervisor: "supervisor",
  loanofficer: "loanofficer",
}
export const fieldAcronyms = {
  email: "email",
  ssn: "SSN",
  dl_number: "DLN",
};

export const LOAN_TYPE = {
  CREDIT_CARD: "Credit Card",
  PERSONAL_LOAN: "Personal Loan",
  SMALL_BUSINESS_LOAN: "Small Business Loan",
};

export const BUILD_TYPE = {
  FUTURE_FAMILY: "futureFamily",
};
